oscilloscope:
  flip_x: false
  edge_compression:
    enabled: false
    range: 0
  pitch:
    follow: false
    cycles: 3
    min_cycle_time: 15.481382
    type: zero_crossing
    alignment: center
  lowpass:
    enabled: false
    order: 1
    cutoff: 1106.3829
  spline:
    segments: 4
    tension: 1
  beam_multiplier: 1.0106384
  window: 302.25797
  bandpass:
    bandwidth: 247.34042
    sidelobe: 11.489362
  rotation: 0

waveform:
  midline: true
  window: 2
  low_mid_split_hz: 250
  mid_high_split_hz: 4000
  slope: 3
  mode: stereo

fft:
  flip_x: false
  markers: false
  cursor: true
  readout_header: true
  smoothing:
    enabled: true
    fall_speed: 54.39362
    hover_fall_speed: 10
    rise_speed: 620.8511
  cqt:
    enabled: false
    bins_per_octave: 16
  sphere:
    enabled: false
    max_freq: 4994
    base_radius: 0.1
  size: 512
  beam_multiplier: 0.61170214
  slope: 6.957447
  limits:
    max_db: -0.9361727
    max_freq: 16034.628
    min_db: -75.414894
    min_freq: 126.96808
  key: sharp
  mode: midside
  frequency_scale: log
  rotation: 0

spectrogram:
  iterative_reassignment: true
  window: 4
  slope: 0
  limits:
    min_freq: 10
    max_freq: 22000
    max_db: -10
    min_db: -60
  frequency_scale: log

window:
  decorations: false
  always_on_top: false
  wayland: true
  default_width: 1280
  default_height: 200
  fps_limit: 24
  theme: matugen.txt

debug:
  log_fps: false
  show_bandpassed: false

phosphor:
  enabled: true
  beam:
    rainbow: false
    energy: 1000
  screen:
    aa_size: 2
    decay:
      fast_frames: 1
      slow_frames: 300
      threshold: 0.3617021
    curvature: 0
    gap: 0
    vignette: 0
    chromatic_aberration: 0
    grain: 0.33510637
  blur:
    radius: 8
    intensity: 0.015957447
  reflections:
    strength: 0

vu:
  momentum:
    enabled: true
    spring_constant: 500
    damping_ratio: 10
  window: 100
  calibration_db: 3
  needle_width: 2
  style: digital
  scale: log

lissajous:
  spline:
    segments: 10
    tension: 1
  beam_multiplier: 0.9574468
  mode: black_hole
  rotation: 1

audio:
  silence_threshold: -70.21277
  sample_rate: 44100
  gain_db: -0.06382942
  engine: pipewire
  device: alsa_output.pci-0000_03_00.6.analog-stereo

lufs:
  mode: momentary
  scale: log
  label: compact

font: /usr/share/fonts/TTF/SpaceMonoNerdFontPropo-Bold.ttf

visualizers:
  main:
    type: hsplit
    ratio: 0.84627575
    children:
      - type: hsplit
        ratio: 0.09380863
        children:
          - id: lufs
          - type: hsplit
            ratio: 0.5
            children:
              - id: spectrum_analyzer
              - id: oscilloscope
      - id: lissajous

plugins:
  {}
