$image = /home/zek/Pictures/__clorinde_and_wriothesley_genshin_impact_drawn_by_lluluchwan__0ea5f20bff44a96803a66d3856f32411 (Edited)_themed_dracula.png

$background = 19,19,24

$error = 255,180,171

$error_container = 147,0,10

$inverse_on_surface = 49,48,54

$inverse_primary = 92,88,145

$inverse_surface = 229,225,233

$on_background = 229,225,233

$on_error = 105,0,5

$on_error_container = 255,218,214

$on_primary = 45,41,96

$on_primary_container = 227,223,255

$on_primary_fixed = 24,18,74

$on_primary_fixed_variant = 68,64,120

$on_secondary = 48,46,66

$on_secondary_container = 228,223,249

$on_secondary_fixed = 27,26,44

$on_secondary_fixed_variant = 70,69,89

$on_surface = 229,225,233

$on_surface_variant = 200,197,208

$on_tertiary = 71,37,56

$on_tertiary_container = 255,216,233

$on_tertiary_fixed = 47,17,34

$on_tertiary_fixed_variant = 96,59,79

$outline = 146,143,153

$outline_variant = 71,70,79

$primary = 197,192,255

$primary_container = 68,64,120

$primary_fixed = 227,223,255

$primary_fixed_dim = 197,192,255

$scrim = 0,0,0

$secondary = 199,196,220

$secondary_container = 70,69,89

$secondary_fixed = 228,223,249

$secondary_fixed_dim = 199,196,220

$shadow = 0,0,0

$source_color = 140,137,163

$surface = 19,19,24

$surface_bright = 58,56,63

$surface_container = 32,31,37

$surface_container_high = 42,41,47

$surface_container_highest = 53,52,58

$surface_container_low = 28,27,32

$surface_container_lowest = 14,14,19

$surface_dim = 19,19,24

$surface_tint = 197,192,255

$surface_variant = 71,70,79

$tertiary = 235,185,208

$tertiary_container = 96,59,79

$tertiary_fixed = 255,216,233

$tertiary_fixed_dim = 235,185,208

