$image = /home/zek/Pictures/wallpapers/clorinde_and_wriothesley_genshin_impact_drawn_by_lluluchwan_0ea5f20bff44a96803a66d3856f32411-Edited-themed_dracula.png

$background = 20,19,24

$error = 255,180,171

$error_container = 147,0,10

$inverse_on_surface = 49,48,54

$inverse_primary = 94,87,145

$inverse_surface = 229,225,233

$on_background = 229,225,233

$on_error = 105,0,5

$on_error_container = 255,218,214

$on_primary = 47,41,95

$on_primary_container = 228,223,255

$on_primary_fixed = 26,18,73

$on_primary_fixed_variant = 70,63,119

$on_secondary = 48,46,65

$on_secondary_container = 229,223,249

$on_secondary_fixed = 27,25,44

$on_secondary_fixed_variant = 71,68,89

$on_surface = 229,225,233

$on_surface_variant = 201,197,208

$on_tertiary = 72,37,55

$on_tertiary_container = 255,216,231

$on_tertiary_fixed = 48,17,33

$on_tertiary_fixed_variant = 97,59,77

$outline = 146,143,153

$outline_variant = 71,70,79

$primary = 199,191,255

$primary_container = 70,63,119

$primary_fixed = 228,223,255

$primary_fixed_dim = 199,191,255

$scrim = 0,0,0

$secondary = 200,195,220

$secondary_container = 71,68,89

$secondary_fixed = 229,223,249

$secondary_fixed_dim = 200,195,220

$shadow = 0,0,0

$source_color = 142,138,162

$surface = 20,19,24

$surface_bright = 58,56,62

$surface_container = 32,31,37

$surface_container_high = 42,41,47

$surface_container_highest = 53,52,58

$surface_container_low = 28,27,32

$surface_container_lowest = 14,14,19

$surface_dim = 20,19,24

$surface_tint = 199,191,255

$surface_variant = 71,70,79

$tertiary = 236,184,206

$tertiary_container = 97,59,77

$tertiary_fixed = 255,216,231

$tertiary_fixed_dim = 236,184,206

