source = colors.conf

$font = Lexend

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = easeInOutExpo,0.87, 0, 0.13, 1
    bezier = easeOutBack, 0.34, 1.56, 0.64, 1
    animation = fadeIn, 1, 7, almostLinear
    animation = fadeOut, 1, 7, almostLinear
    animation = inputFieldDots, 1, 3, easeOutBack
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
}

input-field {
    monitor =
    size = 400,50
    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba($primary,0.8) rgba($source_color,0.7) 45deg
    check_color = rgba($secondary,0.8) rgba($on_secondary_container,0.7) 120deg
    fail_color = rgba($error,1) rgba($on_error,1) 40deg

    font_color = rgb($on_primary_container)
    fade_on_empty = false
    rounding = 5

    font_family = AnonymicePro Nerd Font Propo
    placeholder_text = input password as $USER
    fail_text = $PAMFAIL

    # uncomment if you wish to display a message during authentication
    check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 20
    halign = center
    valign = bottom
}

#Hour
label {
    monitor =
    text = cmd[update:1000] date +"<b>%I</b>"
    text_align = center
    color = rgb($primary)
    font_size = 160
    font_family = AnonymicePro Nerd Font Propo
    shadow_passes = 1
    shadow_size = 5
    position = 0,80
    halign = center
    valign = center
}
#Minutes
label {
    monitor =
    text = cmd[update:1000] date +"<b>%M</b>"
    text_align = center
    color = rgb($primary_fixed)
    font_size = 160
    font_family = AnonymicePro Nerd Font Propo
    shadow_passes = 1
    shadow_size = 5
    position = 0,-80
    halign = center
    valign = center
}

# DATE
 label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d %Y" # update every 60 seconds
    text_align = center
    font_size = 12
    font_family = $font
    color = rgba($on_primary_container,1)
    position = 0, -30
    halign = center
    valign = top
}
