#                                                              
#                                                              
#    ██  ██ ██  ██ █████▄ █████▄  ██     ▄████▄ ███  ██ ████▄  
#    ██████  ▀██▀  ██▄▄█▀ ██▄▄██▄ ██     ██▄▄██ ██ ▀▄██ ██  ██ 
#    ██  ██   ██   ██     ██   ██ ██████ ██  ██ ██   ██ ████▀  
#                                                             
#    █████▄   ▄▄▄   ▄▄▄ ▄▄▄▄▄▄   ▄█████  ▄▄▄  ▄▄  ▄▄ ▄▄▄▄▄     
#    ██▄▄██▄ ██▀██ ██▀██  ██     ██     ██▀██ ███▄██ ██▄▄      
#    ██   ██ ▀███▀ ▀███▀  ██     ▀█████ ▀███▀ ██ ▀██ ██    ▄   
#                                                              
#                                                              

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/start.conf
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/decor.conf
source = ~/.config/hypr/modules/rules.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/binds.conf


# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 2
    # Set to 0 or 1 to disable the anime mascot wallpapers
    
    disable_hyprland_logo = false
    # If true disables the random hyprland logo / anime girl background. :(
    
    always_follow_on_dnd = 1
    anr_missed_pings = 5
    vfr = true
    vrr = 1
}

debug{

  full_cm_proto = true
  disable_logs = true
  
  }

xwayland{

create_abstract_socket = true

}

render{

xp_mode = false
new_render_scheduling = false

}
