wallpaper {
    monitor = 
    path = ~/Pictures/wrnde2a.png
    fit_mode = cover
}

splash = false
splash_offset = 0
splash_opacity = 0.1

# oops they changed lmao
#
# preload = /home/zek/Pictures/wrnde2a.png
# wallpaper = , /home/zek/Pictures/wrnde2a.png
