$backgroundCol = rgb(33, 33, 33)
$color9 = rgb(149, 117, 205)

background {
    monitor =
    path = /home/zek/Pictures/wrnde-desat.png
    blur_size = 5
    blur_passes = 3
    brightness = .6
}
input-field {
    monitor =
    size = 20%, 8%
    outline_thickness = 3
    dots_rounding = -1
    dots_spacing = .5
    dots_fase_time = 300
    inner_color = $backgroundCol
    outer_color = rgba(9575CDee) 
    check_color= $backgroundCol $backgroundCol
    fail_color= rgb(229, 115, 115)
    font_color = rgb(149, 117, 205)
    font_family = Lexend
    fade_on_empty = false
    shadow_color = rgba(0,0,0,0.5)
    shadow_passes = 2
    shadow_size = 2
    rounding = 32
    placeholder_text = <i></i>
    fail_text = <b>FAIL</b>
    fail_timeout = 300
    position = 0, -100
    halign = center
    valign = center
}
#Hour
label {
    monitor =
    text = cmd[update:1000] date +"<b>%I</b>"
    color = rgb(179, 157, 219)
    font_size = 80
    font_family = Lexend
    shadow_passes = 0
    shadow_size = 5
    position = -40, -60
    halign = right
    valign = top
}
#Minutes
label {
    monitor =
    text = cmd[update:1000] date +"<b>%M</b>"
    color = rgb(209, 196, 233)
    font_size = 80
    font_family = Lexend
    shadow_passes = 0
    shadow_size = 5
    position = -40, -150
    halign = right
    valign = top
}
#Date
label {
    monitor =
    text = cmd[update:1000] date +"<b>%A, %B %d, %Y</b>"
    color = rgb(149, 117, 205)
    font_size = 40
    font_family = Lexend
    shadow_passes = 0
    shadow_size = 4
    position = -40,-20
    halign = right
    valign = top
}
#Greetings with user
label {
    monitor =
    text = Hello, <b>$USER</b>
    color = $color9 
    font_size = 40
    font_family = Lexend
    shadow_passes = 0
    shadow_size = 4
    position = 40,-20
    halign = left
    valign = top
}


