background = rgba(18, 19, 24, 0.85)
base = rgba(30, 31, 37, 0.9)
text = rgba(197, 198, 208, 0.9)
alternate_base = rgba(26, 27, 33, 0.9)
bright_text = rgba(227, 226, 233, 1)
accent = rgba(180, 197, 255, 0.9)
accent_secondary = rgba(193, 197, 221, 0.9)

font_family = Readex Pro
font_family_monospace = AnonymicePro Nerd Font Mono

