#                                                     
#                                                     
#    ██▄  ▄██  ▄▄▄  ▄▄  ▄▄ ▄▄ ▄▄▄▄▄▄ ▄▄▄  ▄▄▄▄   ▄▄▄▄ 
#    ██ ▀▀ ██ ██▀██ ███▄██ ██   ██  ██▀██ ██▄█▄ ███▄▄ 
#    ██    ██ ▀███▀ ██ ▀██ ██   ██  ▀███▀ ██ ██ ▄▄██▀ 
# 
#                                                                     
#   See https://wiki.hyprland.org/Configuring/Monitors/

monitor = eDP-1,1366x0,auto,1
monitor = HDMI-A-1,1280x1024,-1280x0,1
