#                                                            
#                                                            
#    ▄████▄ ▄▄ ▄▄ ▄▄▄▄▄▄ ▄▄▄   ▄▄▄▄ ▄▄▄▄▄▄ ▄▄▄  ▄▄▄▄  ▄▄▄▄▄▄ 
#    ██▄▄██ ██ ██   ██  ██▀██ ███▄▄   ██  ██▀██ ██▄█▄   ██   
#    ██  ██ ▀███▀   ██  ▀███▀ ▄▄██▀   ██  ██▀██ ██ ██   ██   
#                                                                                                                          

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wlsunset -l 13.6 -L 121.1 -t 3700
exec-once = waypaper --restore --no-post-command
exec-once = alacritty
exec-once = waybar
exec-once = hyprctl setcursor Posy_Cursor_Black 20
exec-once = nm-applet --indicator
exec-once = jamesdsp -t 
exec-once = blueberry-tray
exec-once = udiskie --tray
exec-once = hypridle
exec-once = swaync
exec-once = swayosd-server
exec-once = wl-paste --watch cliphist store 
exec-once = cliphist wipe
exec-once = systemctl --user start hyprpolkitagent
exec-once = batsignal -b -p -e -m 5 -w 20 -c 10 -d 5 -W 'Battery is at 20%, consider charging' -C 'Battery is at 10%, consider charging' -P 'Battery is charging' -U 'Battery is disconnected from power source' -M notify-send
exec-once = pano-scrobbler -m
exec-once = kdeconnectd && kdeconnect-indicator

