[colors.primary]
background = '#0f150b'
foreground = '#dee5d3'
 
[colors.cursor]
text = '#dee5d3'
cursor = '#c2c9b8' 
 
[colors.vi_mode_cursor]
text = '#0f150b'
cursor = '#67e100' 
 
[colors.search.matches]
foreground = '#42493c' 
background = '#95d4b5' 
 
[colors.search.focused_match]
foreground = '#42493c' 
background = '#67e100' 
 
[colors.footer_bar]
foreground = '#42493c' 
background = '#dee5d3' 
 
[colors.hints.start]
foreground = '#42493c' 
background = '#adcfae' 
 
[colors.hints.end]
foreground = '#42493c' 
background = '#adcfae' 
 
[colors.selection]
text = '#0f150b'
background = '#67e100'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#67e100' 
yellow = '#2e6c00' 
blue = '#67e100' 
magenta = '#95d4b5' 
cyan = '#adcfae' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
