cursor            #bec9c6
cursor_text_color #dde4e2

foreground            #dde4e2
background            #0e1514
selection_foreground  #0e1514
selection_background  #81d5cb
url_color             #b1ccc8

#: black 000000 767676
color0  #000000
color8  #616161
#: red cc0403 f2201f
color1  #ffb4ab
color9  #f29db2
#: green 19cb00 23fd00
color2  #81d5cb
color10 #a4f29d
#: yellow cecb00 fffd00
color3  #006a63
color11 #f2d69d
#: blue 0d73cc 1a8fff
color4  #81d5cb
color12 #9dc0f2
#: magenta cb1ed1 fd28ff
color5  #aec9e6
color13 #f29ddd
#: cyan 0dcdcd 14ffff
color6  #b1ccc8
color14 #9df2e4
#: white dddddd ffffff
color7  #d5dddc
color15 #ffffff

mark1_foreground #00201d
mark1_background #9df2e7
mark2_foreground #051f1d
mark2_background #cce8e4
mark3_foreground #001d33
mark3_background #cee5ff

active_tab_foreground #003733
active_tab_background #81d5cb
inactive_tab_foreground #9df2e7
inactive_tab_background #00504a

active_border_color #81d5cb
inactive_border_color #003733
# bell_border_color #ff5a00
