background #121318
foreground #e3e2e9
cursor #e3e2e9
cursor_text_color #121318
selection_background #dde2f9
selection_foreground #414659
color0 #121318
color1 #947DFF
color2 #94D3FF
color3 #EFE0FF
color4 #90ACD6
color5 #A6A3EE
color6 #9BCEFE
color7 #e3e2e9
color8 #A7A0AC
color9 #AD9BFF
color10 #BDE2FF
color11 #FAF1FF
color12 #B0C3DB
color13 #BEB8F8
color14 #BDDFFF
color15 #FFFFFF
color16 #A88BFF
color17 #C3BACA
color18 #D8BEFF
active_tab_foreground #121318
active_tab_background #b3c5ff
inactive_tab_foreground #c5c6d0
inactive_tab_background #121318
tab_bar_background #121318
