background #19120c
foreground #eee0d5
cursor #eee0d5
cursor_text_color #19120c
selection_background #feddbd
selection_foreground #58432c
color0 #19120c
color1 #D97800
color2 #FFC161
color3 #FFE1C2
color4 #BFA964
color5 #EB965B
color6 #EFC36C
color7 #eee0d5
color8 #B1A090
color9 #FB8D00
color10 #FFD7A0
color11 #FFF2E7
color12 #D4BF92
color13 #F9AE78
color14 #FFD58B
color15 #FFFFFF
color16 #E78600
color17 #CEBAA6
color18 #FFBD6C
active_tab_foreground #19120c
active_tab_background #faba73
inactive_tab_foreground #d4c4b5
inactive_tab_background #19120c
tab_bar_background #19120c
