background #161217
foreground #e9e0e7
cursor #e9e0e7
cursor_text_color #161217
selection_background #efdcf5
selection_foreground #4f4255
color0 #161217
color1 #E34DF3
color2 #FFB6DE
color3 #FFDCF1
color4 #ACA4D7
color5 #CE97DB
color6 #C1C5FF
color7 #e9e0e7
color8 #AE9EA7
color9 #F675FF
color10 #FFD0E7
color11 #FFF0F6
color12 #C0BEDD
color13 #E0AEE6
color14 #D6D8FF
color15 #FFFFFF
color16 #E374DE
color17 #CCB8C3
color18 #FFB1E8
active_tab_foreground #161217
active_tab_background #e0b8f6
inactive_tab_foreground #cdc3ce
inactive_tab_background #161217
tab_bar_background #161217
