cursor            #c4c8bb
cursor_text_color #e1e4d9

foreground            #e1e4d9
background            #11140e
selection_foreground  #11140e
selection_background  #abd290
url_color             #bdcbaf

#: black 000000 767676
color0  #000000
color8  #616161
#: red cc0403 f2201f
color1  #ffb4ab
color9  #eea9ba
#: green 19cb00 23fd00
color2  #abd290
color10 #afeea9
#: yellow cecb00 fffd00
color3  #466731
color11 #eed7a9
#: blue 0d73cc 1a8fff
color4  #abd290
color12 #a9c6ee
#: magenta cb1ed1 fd28ff
color5  #a0cfcf
color13 #eea9dd
#: cyan 0dcdcd 14ffff
color6  #bdcbaf
color14 #a9eee3
#: white dddddd ffffff
color7  #d8ddd5
color15 #ffffff

mark1_foreground #092100
mark1_background #c6eea9
mark2_foreground #141e0d
mark2_background #d9e7ca
mark3_foreground #002020
mark3_background #bbebeb

active_tab_foreground #193706
active_tab_background #abd290
inactive_tab_foreground #c6eea9
inactive_tab_background #2f4f1b

active_border_color #abd290
inactive_border_color #193706
# bell_border_color #ff5a00
