# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#eee0d5"

# Title color for boxes
theme[title]="#fbba74"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e1c1a3"

# Background color of selected item in processes box
theme[selected_bg]="#fbba74"

# Foreground color of selected item in processes box
theme[selected_fg]="#492900"

# Color of inactive/disabled text
theme[inactive_fg]="#d5c3b5"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#becc9b"

# Cpu box outline color
theme[cpu_box]="#9d8e81"

# Memory/disks box outline color
theme[mem_box]="#9d8e81"

# Net up/down box outline color
theme[net_box]="#9d8e81"

# Processes box outline color
theme[proc_box]="#9d8e81"

# Box divider line and small boxes line color
theme[div_line]="#50453a"

# Temperature graph colors
theme[temp_start]="#e1c1a3"
theme[temp_mid]="#fbba74"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e1c1a3"
theme[cpu_mid]="#fbba74"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e1c1a3"
theme[free_mid]=""
theme[free_end]="#58432c"

# Mem/Disk cached meter
theme[cached_start]="#becc9b"
theme[cached_mid]=""
theme[cached_end]="#3f4b25"

# Mem/Disk available meter
theme[available_start]="#fbba74"
theme[available_mid]=""
theme[available_end]="#683d00"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e1c1a3"
theme[download_mid]="#fbba74"
theme[download_end]="#becc9b"

# Upload graph colors
theme[upload_start]="#e1c1a3"
theme[upload_mid]="#fbba74"
theme[upload_end]="#becc9b"